### ISSUE TITLE
p5.capture.umd.js:26 Uncaught ReferenceError: p5 is not defined when importing

### ISSUE THREAD

**Issue by rektadult** [tapioca24/p5.capture#25]
I have a Typescript project that I'm trying to use with the p5.capture API. How can I resolve it? Thanks!

This is the error I'm getting when trying to launch my app:

```
p5.capture.umd.js:26` Uncaught ReferenceError: p5 is not defined
    at Object.<anonymous> (p5.capture.umd.js:26:58118)
    at p5.capture.umd.js:1:62
    at ./node_modules/p5.capture/dist/p5.capture.umd.js (p5.capture.umd.js:1:69)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/js/sketch.ts (sketch.ts:39:22)
    at __webpack_require__ (bootstrap:24:1)
    at startup:6:1
    at startup:6:1
```

here's my package.json, if it helps.
```
{
  "name": "p5.js-es6",
  "version": "1.0.0",
  "description": "Boilerplate for writing p5.js sketches in es6 with babel, webpack and sass.",
  "scripts": {
    "clean": "rimraf dist",
    "dev": "webpack serve --progress --color",
    "serve": "ts-node ./src/js/runServer.ts",
    "prebuild": "npm install",
    "build": "npm run clean && webpack --progress --color --mode=production"
  },
  "repository": {
    "type": "git",
    "url": "git@github.com:mkontogiannis/p5.js-es6.git"
  },
  "author": "Michael Kontogiannis <mkontogiannis@protonmail.com> (https://m.kontogiannis.org/)",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/mkontogiannis/p5.js-es6/issues"
  },
  "homepage": "https://github.com/mkontogiannis/p5.js-es6#README",
  "dependencies": {
    "assert": "^2.0.0",
    "buffer": "^6.0.3",
    "constants-browserify": "^1.0.0",
    "data-forge": "^1.9.6",
    "data-forge-fs": "^0.0.9",
    "express": "^4.18.2",
    "fs": "^0.0.1-security",
    "jsonfile": "^6.1.0",
    "p5": "1.4.1",
    "p5.capture": "^1.4.1",
    "sass": "^1.58.3",
    "stream-browserify": "^3.0.0",
    "util": "^0.12.5"
  },
  "browser": {
    "fs": false,
    "os": false,
    "path": false
  },
  "devDependencies": {
    "@babel/core": "^7.21.0",
    "@babel/preset-env": "^7.20.2",
    "@types/jsonfile": "^6.1.1",
    "@types/p5": "^1.5.0",
    "babel-loader": "^9.1.2",
    "copy-webpack-plugin": "^11.0.0",
    "css-loader": "^6.7.3",
    "prettier": "^2.8.4",
    "rimraf": "^4.2.0",
    "sass-loader": "^13.2.0",
    "style-loader": "^3.3.1",
    "ts-loader": "^9.4.2",
    "typescript": "^4.9.5",
    "webpack": "^5.75.0",
    "webpack-cli": "^5.0.1",
    "webpack-dev-server": "^4.11.1"
  }
}
```

**Comment by tapioca24** [comment]
Hi, @rektadult. Thank you for reporting this one!

Sorry, p5.capture does not support use with module bundlers such as webpack.

**Comment by rektadult** [comment]
thanks @tapioca24 ! closing this.
